import { CanActivate,ExecutionContext,ForbiddenException,Injectable,SetMetadata,UnauthorizedException,createParamDecorator } from '@nestjs/common';
import { Reflector } from '@nestjs/core'; import { JwtService } from '@nestjs/jwt'; import type { AuthUser,Role } from '@cashier/shared'; import { PrismaService } from './prisma.service'; import * as argon2 from 'argon2';
export const Public=()=>SetMetadata('public',true); export const Roles=(...roles:Role[])=>SetMetadata('roles',roles);
export const CurrentUser=createParamDecorator((_d,ctx)=>ctx.switchToHttp().getRequest().user as AuthUser);
@Injectable() export class JwtGuard implements CanActivate { constructor(private r:Reflector,private jwt:JwtService){} canActivate(ctx:ExecutionContext){if(this.r.getAllAndOverride<boolean>('public',[ctx.getHandler(),ctx.getClass()]))return true; const req=ctx.switchToHttp().getRequest(); const raw=req.headers.authorization?.replace(/^Bearer /,''); if(!raw)throw new UnauthorizedException(); try{req.user=this.jwt.verify(raw,{secret:process.env.JWT_ACCESS_SECRET??process.env.JWT_SECRET??'development-only'});return true}catch{throw new UnauthorizedException()} } }
@Injectable() export class RolesGuard implements CanActivate { constructor(private r:Reflector){} canActivate(ctx:ExecutionContext){const roles=this.r.getAllAndOverride<Role[]>('roles',[ctx.getHandler(),ctx.getClass()]); if(!roles)return true; const u=ctx.switchToHttp().getRequest().user as AuthUser; if(!roles.includes(u.role))throw new ForbiddenException(); return true} }
@Injectable() export class WorkerGuard implements CanActivate { constructor(private db:PrismaService){} async canActivate(ctx:ExecutionContext){const req=ctx.switchToHttp().getRequest(); const key=req.headers['x-worker-key']; if(typeof key!=='string')throw new UnauthorizedException(); const workers=await this.db.analytics_workers.findMany({where:{status:{not:'DISABLED'}}}); for(const w of workers)if(await argon2.verify(w.api_key_hash,key)){req.worker=w;return true} throw new UnauthorizedException()} }
export function tenantWhere(user:AuthUser){return user.role==='SUPER_ADMIN'?{}:{organization_id:user.organizationId?BigInt(user.organizationId):undefined}}
export function maskStreamUrl(value:string){try{const u=new URL(value);if(u.password)u.password='***';if(u.username)u.username='***';return u.toString()}catch{return value.replace(/:\/\/([^@]+)@/,'://***:***@')}}
